name: Auto VPN Node Push

on:
  schedule:
    - cron: "40 2 * * *"   # 北京时间 10:40（UTC+0）
    - cron: "0 13 * * *"   # 北京时间 21:00（UTC+0）
  workflow_dispatch:

jobs:
  push_nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SUBSCRIBE_URL: ${{ secrets.SUBSCRIBE_URL }}
        run: python main.py
